### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by MeanBean** [BorisSlonov/hi-fi-end#1]
Hi Boris,

I've got the info from Karina.
Trying to build the project but it does not work, I've got an error linked to this line:
https://github.com/BorisSlonov/hi-fi-end/blob/035834539bb47ac124864803dcf9b63383d4dfd8/gulpfile.babel.js#L3

```
/home/www/hi-fi-end/gulpfile.babel.js:3
import gulp from "gulp";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/home/www/hi-fi-end/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/www/hi-fi-end/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireOrImport (/home/www/hi-fi-end/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

My node/yarn versions (standard debian bullseye): 
```
nodejs -v
v12.21.0
yarnpkg -v
1.22.10
```

**Comment by BorisSlonov** [comment]
Hi Julian,
I think, reinstall node_modules can help you


Hi Boris,

**Comment by MeanBean** [comment]
I completely deleted node_modules before running into this issue.
First time, I did not hence I had a message about darwin (ie. macos) vs linux stuff. (=Error: 'darwin-x64' binaries cannot be used on the 'linux-x64' platform. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install').

So for you those versions of nodejs/yarn should be ok?

**Comment by MeanBean** [comment]
Full commands ran:
```

root@alim:/home/www# git clone https://github.com/BorisSlonov/hi-fi-end
Cloning into 'hi-fi-end'...
remote: Enumerating objects: 33878, done.
remote: Counting objects: 100% (33878/33878), done.
remote: Compressing objects: 100% (23483/23483), done.
remote: Total 33878 (delta 8575), reused 33837 (delta 8540), pack-reused 0 8.46 MiB/s
Receiving objects: 100% (33878/33878), 97.27 MiB | 13.93 MiB/s, done.
Resolving deltas: 100% (8575/8575), done.
Updating files: 100% (36081/36081), done.
root@alim:/home/www# yarnpkg global add gulp-cli
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "gulp-cli@2.3.0" with binaries:
      - gulp
Done in 1.59s.
root@alim:/home/www# yarnpkg global add bem-tools-core
yarn global v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "bem-tools-core@0.0.3" with binaries:
      - bem
Done in 2.22s.
root@alim:/home/www# cd hi
hi-fi-end/ highNorma/
root@alim:/home/www# cd hi
hi-fi-end/ highNorma/
root@alim:/home/www# cd hi-fi-end/
root@alim:/home/www/hi-fi-end# rm -fr node_modules/
root@alim:/home/www/hi-fi-end# yarnpkg
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > babel-eslint@10.1.0" has unmet peer dependency "eslint@>= 4.12.1".
[4/4] Building fresh packages...
Done in 29.98s.
root@alim:/home/www/hi-fi-end# yarnpkg run dev
yarn run v1.22.10
$ gulp
[21:36:04] Requiring external module @babel/register
/home/www/hi-fi-end/gulpfile.babel.js:3
import gulp from "gulp";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/home/www/hi-fi-end/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/www/hi-fi-end/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at requireOrImport (/home/www/hi-fi-end/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@alim:/home/www/hi-fi-end#

```

**Comment by MeanBean** [comment]
Found this: https://github.com/gulpjs/gulp#use-latest-javascript-version-in-your-gulpfile
Added a .babelrc file

Seems to pass that hurdle.

Now:
```
root@alim:/home/www/hi-fi-end# yarnpkg run dev
yarn run v1.22.10
$ gulp
[22:04:17] Requiring external module @babel/register
[22:04:20] Using gulpfile /home/www/hi-fi-end/gulpfile.babel.js
[22:04:20] Starting 'default'...
[22:04:20] Starting 'clean'...
[22:04:20] Finished 'clean' after 31 ms
[22:04:20] Starting 'views'...
[22:04:20] Starting 'styles'...
[22:04:20] Starting 'scripts'...
[22:04:20] Starting 'images'...
[22:04:20] Starting 'webp'...
[22:04:20] Starting 'sprites'...
[22:04:20] Starting 'fonts'...
[22:04:20] Starting 'favicons'...
[22:04:21] Plumber found unhandled error:
 Error in plugin "gulp-sass"
Message:
    src/blocks/_modules.scss
Error: File to import not found or unreadable: modules/layout/page-offer/page-offer.
        on line 23 of src/blocks/_modules.scss
        from line 7 of src/styles/main.scss
>> @import "modules/layout/page-offer/page-offer";

   ^

Details:
    status: 1
    file: /home/www/hi-fi-end/src/blocks/_modules.scss
    line: 23
    column: 1
    formatted: Error: File to import not found or unreadable: modules/layout/page-offer/page-offer.
        on line 23 of src/blocks/_modules.scss
        from line 7 of src/styles/main.scss
>> @import "modules/layout/page-offer/page-offer";

   ^

    messageFormatted: src/blocks/_modules.scss
Error: File to import not found or unreadable: modules/layout/page-offer/page-offer.
        on line 23 of src/blocks/_modules.scss
        from line 7 of src/styles/main.scss
>> @import "modules/layout/page-offer/page-offer";

   ^

    messageOriginal: File to import not found or unreadable: modules/layout/page-offer/page-offer.
    relativePath: src/blocks/_modules.scss

[22:04:21] CSS files 0 items
[22:04:21] Finished 'styles' after 902 ms
[22:04:22] Images dist/img/bull_1.png
[22:04:22] Favicons dist/img/favicons/favicon-16x16.png
[22:04:22] Favicons dist/img/favicons/favicon-32x32.png
[22:04:22] Images dist/img/collor-ball-left.png
[22:04:23] Fonts dist/fonts/webfonts/fa-brands-400.woff
[22:04:23] Favicons dist/img/favicons/favicon-48x48.png
[22:04:23] Images dist/img/cursor.png
[22:04:23] Fonts dist/fonts/webfonts/fa-regular-400.woff
[22:04:23] Sprites dist/img/sprites/sprite.svg
[22:04:23] Images dist/img/bull_1.webp
[22:04:23] Favicons dist/img/favicons/favicon.ico
[22:04:23] Images dist/img/exp1.png
[22:04:23] Sprites dist/img/sprites/intermediate-svg/2d-circle.svg
[22:04:23] Fonts dist/fonts/webfonts/fa-solid-900.woff
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-57x57.png
[22:04:23] Sprites dist/img/sprites/intermediate-svg/aproach-table.svg
[22:04:23] Images dist/img/exp2.png
[22:04:23] Fonts dist/fonts/webfonts/fa-brands-400.woff2
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-60x60.png
[22:04:23] Sprites dist/img/sprites/intermediate-svg/aproach-table-fr.svg
[22:04:23] Images dist/img/collor-ball-left.webp
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-72x72.png
[22:04:23] Images dist/img/expertise.png
[22:04:23] Fonts dist/fonts/webfonts/fa-regular-400.woff2
[22:04:23] Sprites dist/img/sprites/intermediate-svg/map.svg
[22:04:23] Sprites 5 items
[22:04:23] Finished 'sprites' after 3.1 s
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-76x76.png
[22:04:23] Images dist/img/light.png
[22:04:23] Fonts dist/fonts/webfonts/fa-solid-900.woff2
[22:04:23] Fonts 6 items
[22:04:23] Finished 'fonts' after 3.17 s
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-114x114.png
[22:04:23] Images dist/img/cursor.webp
[22:04:23] Images dist/img/logo.png
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-120x120.png
[22:04:23] Images dist/img/mission.png
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-144x144.png
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-152x152.png
[22:04:23] Images dist/img/neon-ball.png
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-167x167.png
[22:04:23] Images dist/img/neon-dot.png
[22:04:23] Images dist/img/exp1.webp
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-180x180.png
[22:04:23] Images dist/img/news-bg.png
[22:04:23] Favicons dist/img/favicons/apple-touch-icon-1024x1024.png
[22:04:24] Images dist/img/pole_it-1.png
[22:04:24] Favicons dist/img/favicons/apple-touch-icon.png
[22:04:24] Favicons dist/img/favicons/apple-touch-icon-precomposed.png
[22:04:24] Favicons 17 items
[22:04:24] Finished 'favicons' after 3.95 s
[22:04:24] Images dist/img/pole_it-2.png
[22:04:24] Images dist/img/exp2.webp
[22:04:24] Images dist/img/pole_it-3.png
[22:04:24] Images dist/img/project.png
[22:04:24] Images dist/img/square-dots.png
[22:04:24] 'scripts' errored after 4.66 s
[22:04:24] Error in plugin "webpack-stream"
Message:
    Entry module not found: Error: Can't resolve './src/js/import/page-about/page-about.js' in '/home/www/hi-fi-end'
resolve './src/js/import/page-about/page-about.js' in '/home/www/hi-fi-end'
  using description file: /home/www/hi-fi-end/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/www/hi-fi-end/package.json (relative path: ./src/js/import/page-about/page-about.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js.json doesn't exist
      as directory
        /home/www/hi-fi-end/src/js/import/page-about/page-about.js doesn't exist
Details:
    domainThrown: true

[22:04:24] 'default' errored after 4.69 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by MeanBean** [comment]
@BorisSlonov  any news?
Looks like some files are missing.

**Comment by BorisSlonov** [comment]
I update files, please, try now

**Comment by MeanBean** [comment]
Build is ok now. Thanks
